### ISSUE TITLE
i have an idea

### ISSUE THREAD

**Issue by nonamebatbai** [Dadangdut33/Screen-Translate#10]
![hfg](https://user-images.githubusercontent.com/55612825/140649181-ec48b458-acaa-481f-83c8-274f8046a548.png)

pretty good results.
so my idea is you can create an extra window. and darken the surroundings. to see the text better and the "Text Capture Area" will work better and the "Text Capture Area" window must be overlaid on the new window to darken the surroundings to work properly.
![hfg12](https://user-images.githubusercontent.com/55612825/140649508-d435f930-dda3-44b2-adc1-e05f67c48667.png)
I darkened the "Text Capture Area" and used "Capture Area Settings" to translate and got the exact same result as the picture above.

**Comment by Dadangdut33** [comment]
Might be a good idea, will work on this soon thanks for the suggestion!

**Comment by nonamebatbai** [comment]
> Might be a good idea, will work on this soon thanks for the suggestion!

thank you very much

**Comment by Dadangdut33** [comment]
I have added it in [1.8.1](https://github.com/Dadangdut33/Screen-Translate/releases/tag/V1.8.1) Once again, thanks for all the feedback and suggestion! :D
