### ISSUE TITLE
Thank you for creating the software. But can you help me to solve the following problems.

### ISSUE THREAD

**Issue by nonamebatbai** [Dadangdut33/Screen-Translate#4]
I tried translating the game tales of arise. doesn't seem to work well with large fonts. And often appear "Please enter some text".
Does (Opacity) affect the effectiveness of text detection in the game?
How should I adjust the Offset X , Y , W , H, for the software to work best
![image](https://user-images.githubusercontent.com/55612825/136547103-dd63d262-0c64-4ca8-be89-4f64b7cbc76f.png)

**Comment by Dadangdut33** [comment]
Thanks for reaching out, if you are not using multiple monitors and your screen scaling is 100% you don't need to set any offset. 

As for why it often does not capture any text, it might be because the background behind the text is not clear enough.  Tesseract could not detect any text if the background is not clear enough. If there is a setting to set the background opacity behind the text in the game maybe you could try to make it more opaque. 

I will try to add more OCR engines, maybe there are better OCR out there. Until then maybe you can try another software.
I'm sorry and I hope it helps :)

**Comment by nonamebatbai** [comment]
I find this software very good . I hope you will improve it even better

**Comment by nonamebatbai** [comment]
> Thanks, I will try to make it even better :D

Thank you very much for the tool. Now it has become more convenient.
I have a question. If later this tool is not developed anymore . but the Tesseract software is still evolving. So I just need to download Tesseract software and upgrade, right?

**Comment by Dadangdut33** [comment]
> I have a question. If later this tool is not developed anymore. but the Tesseract software is still evolving. So I just need to download Tesseract software and upgrade, right?

I don't know about this one if the API and the methods to use it in python do not change much, then it should be ok to just upgrade the tesseract version.

> Is Tesseract software an OCR?

Yea it is a free open source OCR engine, sponsored by google. You can take a look at their [repository](https://github.com/tesseract-ocr/tesseract) if you are interested.

> If later this tool is not developed anymore

I'm still planning on improving it as long as I have the free time to do it, so you don't have to worry about that for now, but if somehow I dropped this project you can just fork it and improve it on your own, feel free to do so

**Comment by nonamebatbai** [comment]
It is very inconvenient if the program does not detect the text and then displays that line, making me control the mouse to turn it off, then I will miss the next conversation.

**Comment by nonamebatbai** [comment]
> > If "grayscale" is enabled, the error "No text entered:please enter some text?" will often appear.
> 
> ah, looks like it still haven't change much huh. Maybe another ocr engine will help, i will try to add more engine in the future.
> 
> I could not solve the problem of that for now, after all i think the tessdata of tesseract by default is not that great when it's hard to distinguish the background and the text. The solution I think is only if there is a trained tesssdata of the language on a certain bright background, you could try to train it yourself if you can.
> 
> > This is also a problem with many OCR applications. but i think your software is the best
> 
> Haha, thanks for the kind words :)

you really did a great job. I will wait for better upgrades from you

**Comment by nonamebatbai** [comment]
Thank you for fixing my software. but show no text entered alert doesn't seem to work when. still appear "No text entered:please enter some text?"
and i think 1.7.1 version works better than 1.7.2

**Comment by nonamebatbai** [comment]
with Capture and Translate seems to be slower than previous versions. despite setting time delay = 0

**Comment by nonamebatbai** [comment]
> > Thank you for fixing my software. but show no text entered alert doesn't seem to work when. still appear "No text entered:please enter some text?"
> 
> What do you mean? I didn't change anything related to that there shouldn't be any problem, did you make sure that the alert is turned off on the setting?

if "show no text entered alert" is checked, it will no longer show ""No text entered:please enter some text?" right?

**Comment by nonamebatbai** [comment]
> > with Capture and Translate seems to be slower than previous versions. despite setting time delay = 0
> 
> I think this one is related to the ocr enhancement, cv2 needs quite some time to process the image so it's not really a bug.
> 
> > if "show no text entered alert" is checked, it will no longer show ""No text entered:please enter some text?" right?
> 
> No, you got it backward, If it is checked it will show the alert.
> 
> Edit: If you found a bug unrelated to this thread you should create a new issue in order to avoid flooding this issue

ok. I found the software to be perfect
thank you so much
