### ISSUE TITLE
 Can you add more OCR engines to your software? 

### ISSUE THREAD

**Issue by nonamebatbai** [Dadangdut33/Screen-Translate#9]
![Untitled](https://user-images.githubusercontent.com/55612825/140482257-d4ada685-c6cf-4d21-b645-d3d67e49d3e1.png)
This dialogue with black border translates very accuratel
![Untitled1](https://user-images.githubusercontent.com/55612825/140482744-5aa0131e-809e-40bc-932a-6237b6972798.png)
y
or the dark scene, the translation is also very accurat
![Untitled 2](https://user-images.githubusercontent.com/55612825/140482968-e4592852-e155-4a9d-97a6-e2e6156f1a36.png)
e
but the light scene cannot be translated.
Can you solve this problem?
Why does the software not work when the scene is bright?

**Comment by Dadangdut33** [comment]
> Why does the software not work when the scene is bright?
It's not just that, the background is also abstract there and your capture area is too big which makes it harder to detect the word

> Can you solve this problem?
I don't think I could do anything else. I have improved it the best I can.

> Can you add more OCR engines to your software?
I haven't found any other OCR engine that is as practical and has many language support like tesseract. So I don't think I will add any soon.  But if you have some suggestions, do let me know

**Comment by nonamebatbai** [comment]
> > Why does the software not work when the scene is bright?
> 
> It's not just that, the background is also abstract there and your capture area is too big which makes it harder to detect the word
> 
> > Can you solve this problem?
> 
> I don't think I could do anything else. I have improved it the best I can.
> 
> > Can you add more OCR engines to your software?
> 
> I haven't found any other OCR engine that is as practical and has many language support like tesseract. So I don't think I will add any soon. But if you have some suggestions, do let me know

Can you create a matte black border for the text lines when you press translate?

**Comment by Dadangdut33** [comment]
I won't be adding another OCR soon, so this will be closed. And, for the border suggestion will be Continued in [#10 ](https://github.com/Dadangdut33/Screen-Translate/issues/10)
